language: c
compiler:
    - clang
    - gcc
install:
    - git submodule update --init --recursive
branches:
    only:
        - master
script:
    - "echo debug build c11 standard"
    - make std=c11
    - ./examples/throughput
    - tail scribedebug.log
    - make clean
    - "echo debug build c99 standard"
    - make std=c99
    - ./examples/throughput
    - tail scribedebug.log
    - make clean
    - "echo regular build c11 standard"
    - make std=c11 OPTFLAGS=-DNDEBUG
    - ./examples/throughput
    - make clean
    - "echo regular build c11 standard"
    - make std=c99 OPTFLAGS=-DNDEBUG
    - ./examples/throughput
    - make clean
    - "echo done"
